### ISSUE TITLE
2주차 [6/17 ~ 23] 시호 TODO

### ISSUE THREAD

**Issue by KitsuneSiho** [KitsuneSiho/POPSTIVER_GRADLE_MVC#13]
- [x] Board Mapper 설계
- [x] DB -> 게시판으로 리스트형태로 데이터 불러오기 구현
- [x] DB에 삽입 구현
- [x] 삭제->DB삭제 구현
- [x] 게시판 누르기-> 상세정보 불러오기 구현(호준이형이 해줬다 달달하군!)
