### ISSUE TITLE
2주차 [6/17 ~ 23] 강현욱 TODO

### ISSUE THREAD

**Issue by harrykang0805** [KitsuneSiho/POPSTIVER_GRADLE_MVC#14]
- [x] Maven 컨트롤 이슈로 인한 Gradle로 프로젝트 빌드 변경
- [ ] 게시판 기능 구현 시작
- [ ] 메인 페이지 기능 구현 시작
- [ ] 소켓 다시 도전..
