### ISSUE TITLE
3주차 [6/24 ~ 30] 시호 TODO

### ISSUE THREAD

**Issue by KitsuneSiho** [KitsuneSiho/POPSTIVER_GRADLE_MVC#20]
- [x] Board Entity정의
- [x] Board DAO(Repository), DTO 설계
- [x] BoardController, Service 구현후 프론트엔드 출력 구현(공지, 자게등등)
- [x] Report(제보)랑 주최자 계정에서 정보입력 -> DB 삽입 -> DB 출력 구현
- [ ] +a 댓글구현
