### ISSUE TITLE
3주차 [6/24 ~ 30] 이호 TODO 

### ISSUE THREAD

**Issue by 2Hojune** [KitsuneSiho/POPSTIVER_GRADLE_MVC#22]
- [ ]  방문자 성별, 리서치 경로 통계(chart.js 이용) : 태그를 통한 관심도 통계 추출
- [ ] 태그추천 : 파이썬 BERT 모델 이용. 자연어 처리를 통해 태그 추출, 이를 토대로 태그 구현 
- [ ]  태그 구현 : 마이페이지
- [ ]  태그 구현 : 축제 상세화면에 태그
