### ISSUE TITLE
3주차 [6/24 ~ 30] 강현욱 TODO 

### ISSUE THREAD

**Issue by harrykang0805** [KitsuneSiho/POPSTIVER_GRADLE_MVC#23]
- [ ] 메인페이지 오픈예정 및 인기 이벤트 출력

- [ ] - 관리자 페이지 :

- [ ] -좋아요 누른 통계

- [ ] -조회수 많은 통계

- [ ] -회원관리 : 삭제가능 하도록

- [ ] - 비즈니스 문의 :  비즈니스 문의 : 관리자 페이지에서만 읽을 수 있도록 구현. 관리자가 확인 후 직접 올리는 방식
