### ISSUE TITLE
3주차 [6/24 ~ 30] 문재영 TODO

### ISSUE THREAD

**Issue by answodud** [KitsuneSiho/POPSTIVER_GRADLE_MVC#26]
- [ ] 카카오맵 API 이용해서 근처 행사 페이지 구현
- [ ] 행사 타입별, 지역별 지도 검색 기능 구현
- [ ] 자유게시판 글 작성 기능 구현
- [ ] 세션 활용한 조회수 기능 구현
