### ISSUE TITLE
4주차 [7/1 ~ 5] 강현욱 TODO

### ISSUE THREAD

**Issue by harrykang0805** [KitsuneSiho/POPSTIVER_GRADLE_MVC#28]
- [ ] 관리자 대쉬보드 안정화

- [ ] 채팅서비스 부가기능 및 안정화

- [ ] 오픈예정 및 인기 게시글 메인 출력 안정화

- [ ] 시큐리티 권한 작업 설정
