### ISSUE TITLE
4주차 [7/1 ~ 7/7] 문재영 TODO

### ISSUE THREAD

**Issue by dazai1936** [KitsuneSiho/POPSTIVER_GRADLE_MVC#29]
- [ ] 좋아요 기능 페이지별 연동
- [ ] 좋아요 카운트
- [ ] 메인 더보기 페이지
- [ ] 달력, 검색 결과페이지 CSS 수정
- [ ] 버그 수정
- [ ] 발표 스크립트 작성
