### ISSUE TITLE
4주차 [7/1 ~ 7/5] 시호 TODO

### ISSUE THREAD

**Issue by KitsuneSiho** [KitsuneSiho/POPSTIVER_GRADLE_MVC#30]
- [x] 관리자권한 게시글 삭제기능 추가
- [x] 유저별 게시글 수정 및 삭제기능 추가
- [x] 게시글 수정시 이전 게시글 내용 불러오는 기능 추가(Ajax)
- [x] 코드 안정화
- [x] 비즈니스/리포트 게시물 데이터베이스 컬럼 동기화
- [x] BoardRepository 코드 최적화, 버그수정
- [x] 게시글 맵핑버그 수정

**Comment by KitsuneSiho** [comment]
complet
