### ISSUE TITLE
1주차 [6/10 ~ 14] 시호 TODO

### ISSUE THREAD

**Issue by KitsuneSiho** [KitsuneSiho/POPSTIVER_GRADLE_MVC#4]
- [x]  root config, servlet config, web config 구조설정
- [x] db.properties 로 mysql서버와 연결
- [x] erp 설계 최종검토, db에 탑업(테이블 제작)
- [x] 외래키, 관계설정.테이블 조인 설계
- [ ] 트리거설계, 제작
- [x] Mapper.java 설계
- [ ] Mapper.xml 쿼리작성(회원 조인, 로그인 인증)
- [x] (오버워크) main페이지 탑업
- [x] (오버워크) CSS/FronTend Resources 경로 매핑
- [x] (과로사) 에셋리소스 경로 연결
- [x] (과로사) 자카르타, 스프링프레임워크 6.X.X 업그레이드
